#cloud-config

hostname: dnspooq-server
timezone: Asia/Tokyo

users:
  - name: ubuntu
    plain_text_passwd: ubuntu
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, docker
    shell: /bin/bash

chpasswd:
  list: |
    ubuntu:ubuntu
    root:ubuntu
  expire: false

ssh_pwauth: true
disable_root: false

write_files:
  - path: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
      nameserver 8.8.4.4
    owner: root:root
    permissions: '0644'

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - net-tools
  - dnsutils

runcmd:
  - systemctl disable systemd-resolved
  - systemctl stop systemd-resolved
  - sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#PermitRootLogin.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - sleep 10
  - ping -c 3 google.com
  - apt update
  - apt upgrade -y
  - apt install -y docker.io docker-compose
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker ubuntu
  - mkdir -p /home/ubuntu/dnspooq
  - chown ubuntu:ubuntu /home/ubuntu/dnspooq
  - echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
  - sysctl -p
  - docker --version
  - docker-compose --version