#cloud-config

hostname: dnspooq-server
timezone: Asia/Tokyo

chpasswd:
  list: |
    ubuntu:ubuntu
    root:ubuntu
  expire: false

ssh_pwauth: true
disable_root: false

write_files:
  - path: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
      nameserver 8.8.4.4
    owner: root:root
    permissions: '0644'

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - wget
  - net-tools
  - dnsutils
  - rsync
  - openssh-client
  - tcpdump
  - wireshark-common
  - iptables-persistent
  - python3
  - python3-pip
  - vim
  - htop

runcmd:
  - systemctl disable systemd-resolved
  - systemctl stop systemd-resolved
  - sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#PermitRootLogin.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - sleep 10
  - ping -c 3 google.com
  - apt update
  - apt upgrade -y
  - apt install -y apt-transport-https ca-certificates curl gnupg lsb-release git wget net-tools dnsutils rsync openssh-client tcpdump wireshark-common iptables-persistent python3 python3-pip vim htop
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update
  - apt install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker ubuntu
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - mkdir -p /home/ubuntu/dnspooq
  - chown ubuntu:ubuntu /home/ubuntu/dnspooq
  - echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
  - sysctl -p
  - docker --version
  - docker-compose --version